### ISSUE TITLE
Error in creating a project

### ISSUE THREAD

**Issue by ehsun-zad** [loentar/ngrest#31]
Hi,
When I try to create a project (like ngrest creat echo) after executing the last command (ngrest) the following error occurs:
Fatal: cannot change to '/home/esi/.ngrest/ngrest': no such file or directory
What is .ngrest? How could I make it?

**Comment by khairy-mohamed** [comment]
**.ngrest** is where your service deployed to . 
if you can't create the project you may try to switch to root by 
`sudo -s `
and then try to create the project . 
it may be a permission problem .

**Comment by loentar** [comment]
No, it should be the permission problem, because ngrest is deployed under user by default.

As I understand you didn't used one-liner script to install and configure ngrest. This is not the preferred way and much simpler is to install it as suggested in README:

```
wget -qO- http://bit.ly/ngrest | bash
```

I believe you used CMake to create makefiles and build ngrest. In this case you should point `ngrest` script where ngrest sources and build directory are located. 

To solve the problem, please try this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ngrest/EfaabPS7xMA/NdMnPMd5BQAJ
